export { WorkExperiences} from './PageFeature/WorkExperiences'
export {Skills} from './PageFeature/Skills'
export {Educations} from './PageFeature/Educations'
export {Slider} from './atoms/Slider'
export {Icon} from './atoms/Icon'